### ISSUE TITLE
Twilio_name: config issue

### ISSUE THREAD

**Issue by mababio** [mababio/python_stuff#8]
Getting this error on a clean docker system:

`Traceback (most recent call last):
  File "/usr/local/bin/twil_num", line 11, in <module>
    load_entry_point('twilio-name==1.0', 'console_scripts', 'twil_num')()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2409, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2415, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/site-packages/twilio_name-1.0-py3.6.egg/twilio_name/twilio_helper.py", line 7, in <module>
    from config import config
ModuleNotFoundError: No module named 'config'`

**Comment by mababio** [comment]
solved by updating setup.py package list [here](https://github.com/mababio/python_stuff/commit/b9102e2933d766b704ae5c36491416818c3b0dcf)
